### ISSUE TITLE
bug: pickVideos not working in android12 

### ISSUE THREAD

**Issue by ysneo** [capawesome-team/capacitor-file-picker#81] opened 2023-01-22 02:37 UTC
**Plugin version:**

0.5.9 latest

**Platform(s):**

Capacitor 4 ， android 12

**Current behavior:**

choose other app file explore to pick file ,no photo album
![image](https://user-images.githubusercontent.com/17615113/213898017-29a76e28-719f-44b9-a810-3c95ac61b4b3.png)

**Expected behavior:**

**be in photo album to choose the video** 

**Steps to reproduce:**

**Related code:**

```
  const result = await FilePicker.pickVideos({
            multiple: false, // 限制一个
          }).catch(er => {
            console.error(er.message);
          });
```

**Other information:**

**Comment by robingenz** [comment] 2023-01-22 07:23
If you don't want to use the photo album to pick videos, you can just use the ['pickFiles(...)'](https://github.com/capawesome-team/capacitor-file-picker#pickfiles) method with a mime type (e.g. 'video/mp4').

**Comment by ysneo** [comment] 2023-01-22 07:29
> If you don't want to use the photo album to pick videos, you can just use the ['pickFiles(...)'](https://github.com/capawesome-team/capacitor-file-picker#pickfiles) method with a mime type (e.g. 'video/mp4').

I need to use pickVideo to open photo album; but in my real android 12 phone, 
the function pickVideo open the app "mixplore' not photo album,  confusing. Like the pic below, and cant choose video
![image](https://user-images.githubusercontent.com/17615113/213905361-4402ac58-6f08-4a86-8dd1-f24b40e11b9e.png)

**Comment by robingenz** [comment] 2023-01-22 07:57
This seems like a configuration issue on your local device. The plugin just opens the default album app. 
Can you change the default album app in your system settings?

**Comment by ysneo** [comment] 2023-01-22 08:01
yes my default is album; pic below;  But pickVideo open another app.
![image](https://user-images.githubusercontent.com/17615113/213906271-3d364933-821c-4fc6-abdf-1f809a82ed59.png)

**Comment by robingenz** [comment] 2023-01-22 09:35
Can you pick videos with the album app in other apps?

**Comment by ysneo** [comment] 2023-01-22 12:35
> Can you pick videos with the album app in other apps?

yes, other app pick the video is ok

**Comment by robingenz** [comment] 2023-01-22 12:40
Okay, in this case you need to debug it yourself on your local device because I cannot reproduce the issue on my Pixel 5 and I don’t have access to your device and configuration. 

Feel free to send me a PR with a fix.

**Comment by ysneo** [comment] 2023-01-22 12:50
> Okay, in this case you need to debug it yourself on your local device because I cannot reproduce the issue on my Pixel 5 and I don’t have access to your device and configuration.
> 
> Feel free to send me a PR with a fix.

I mean other app like wechat,whatsapp can choose video;  but use capacitor plugin pickVideo function can't choose a video.

**Comment by robingenz** [comment] 2023-01-22 12:59
Yes, I know, but I cannot debug it myself because I cannot reproduce the issue on my device and don’t have access to your device and device configuration. 
So you need to debug it yourself.
As I said, PRs are welcome.

**Comment by ysneo** [comment] 2023-01-22 13:06
ok

**Comment by ysneo** [comment] 2023-01-22 16:05
@robingenz 

I debug the function , here is the error, Can you come up with problem

```
Photo.vue?8e26:182 No Activity found to handle Intent { act=android.intent.action.PICK typ=video/* (has extras) }
```

![image](https://user-images.githubusercontent.com/17615113/213926057-577af009-b73d-4562-99ec-678f246577c4.png)

**Comment by robingenz** [comment] 2023-01-23 14:31
@ysneo Maybe, please try this dev version and let me know if it helps:

```
npm i @capawesome/capacitor-file-picker@0.5.9-dev.a974753.1674484205
```

**Comment by ysneo** [comment] 2023-01-28 00:59
> @ysneo Maybe, please try this dev version and let me know if it helps:
> 
> ```
> npm i @capawesome/capacitor-file-picker@0.5.9-dev.a974753.1674484205
> ```

still not work, but I change to use "Intent.ACTION_GET_CONTENT", then I can pick video now;

**Comment by robingenz** [comment] 2023-01-30 18:01
This should be the same as the ['pickFiles(...)'](https://github.com/capawesome-team/capacitor-file-picker#pickfiles) method which i've suggested [here](https://github.com/capawesome-team/capacitor-file-picker/issues/81#issuecomment-1399420348).

In this case i will close this issue.

**Closed by robingenz** 2023-01-30 18:01 UTC
Labels: platform: android
